#!/bin/bash
# This service sets up and installs the libraries needed for Python Flask and
# configures Apache to set up a wsgi gateway on CentOS, Red Hat, Debian and Ubuntu
#
# Copyright 2016 Cisco Systems
# Author Matt Day
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice, original author and this notice are preserved. This file is
# offered as-is, without any warranty.

# Load cloud centre libraries and logging:
exec > >(tee -a /usr/local/osmosix/logs/service.log) 2>&1
OSSVC_HOME=/usr/local/osmosix/service
. /usr/local/osmosix/etc/.osmosix.sh
. /usr/local/osmosix/etc/userenv
. $OSSVC_HOME/utils/cfgutil.sh
. $OSSVC_HOME/utils/install_util.sh
. $OSSVC_HOME/utils/os_info_util.sh

# Detect the OS we're running
if [[ -x /usr/bin/apt-get ]]; then
	FLAVOUR="debian"
	PACKAGES="python-flask python curl apache2 libapache2-mod-wsgi unzip"
	PKG_INSTALL="apt-get -y install"
	PKG_UPDATE="apt-get -y update"
	PKG_UPGRADE="apt-get -y upgrade"
	HTTPD_SERVICE=apache2
elif [[ -x /usr/bin/yum ]]; then
	FLAVOUR="redhat"
	PACKAGES="python-flask python curl httpd mod_wsgi unzip python-jinja2"
	PKG_INSTALL="yum -y install"
	PKG_UPDATE="yum -y update"
	PKG_UPGRADE=""
	HTTPD_SERVICE=httpd
else
	log '[ERROR] Cannot detect operating system'
	# Error out - can't detect OS!
	exit 1
fi

# Is a proxy configured or needed?
# Variables:
# ENABLE_PROXY - If set to "Enabled" proxy support will be turned on
# PROXY - proxy to use, e.g. http://proxy.esl.cisco.com:80/
# NO_PROXY_HOSTS - hosts to never proxy, e.g. .cisco.com
# NO_PROXY_RANGE - /24 subnets to not proxy, e.g. 10.52.208 10.51.8
if [[ "$ENABLE_PROXY" = Enabled ]] && [[ -z $PROXY ]]; then
    export PROXY=$PROXY
    export proxy=$PROXY
    export http_proxy=$PROXY
    export https_proxy=$PROXY
    export ftp_proxy=$PROXY
    export HTTP_PROXY=$PROXY
    export HTTPS_PROXY=$PROXY
    export FTP_PROXY=$PROXY
    if [[ -z $NO_PROXY_HOSTS ]]; then
        no_proxy=$(echo $NO_PROXY_HOSTS | sed 's/ /,/g')
    fi
    if [[ -z $NO_PROXY_RANGE ]]; then
        for ip in $NO_PROXY_RANGE; do
            no_proxy="$no_proxy,$(echo $ip.{0..255} | sed 's/ /,/g')"
        done
        export no_proxy
        export NO_PROXY=$no_proxy
    fi
fi

upgrade() {
	log "[UPGRADE] Updating OS with command $PKG_UPDATE"
	$PKG_UPDATE
	if (( $? > 0 )); then
		log '[ERROR] OS Update failed'
		exit 1
	fi
	# Debian requires two commands update & upgrade, so run them both
	if [[ "$FLAVOUR" = debian ]]; then
		log "[UPGRADE] Upgrading OS with command $PKG_UPGRADE"
		$PKG_UPGRADE
		if (( $? > 0 )); then
			log '[ERROR] OS Update failed'
			exit 1
		fi
	fi
}

# Update the OS and install the needed libraries
install() {
	log '[INSTALL] Requesting OS upgrade'
	# Run OS upgrade
	upgrade
	# Install needed packages
	log "[INSTALL] Installing required packages with command $PKG_INSTALL $PACKAGES"
	$PKG_INSTALL $PACKAGES
	if (( $? > 0 )); then
		log '[ERROR] Package installation failed'
		exit 1
	fi

	# Debian based distros need to explicitly enable the new mods etc
	if [[ "$FLAVOUR" = debian ]]; then
		log '[INSTALL] Running debian-flavour specific commands'
		# Enable wsgi module and disable default vhost
		a2enmod wsgi
		a2dissite 000-default default-ssl
		# Make sure the apache service is stopped
	fi
	log '[INSTALL] Stopping httpd service (in case it is enabled)'
	service $HTTPD_SERVICE stop
}

deploy() {
	log '[DEPLOY] Deploying app'
	curl -o flaskapp.zip "$SCRIPT_LOCATION"
	if (( $? > 0 )) || [[ ! -f flaskapp.zip ]]; then
		log '[ERROR] Script download failed'
		exit 127
	fi

	WEB_ROOT="/var/www/flaskapp"
	APP_NAME=`echo $SCRIPT_NAME | sed 's/\.py$//'`

	if [[ "$FLAVOUR" = debian ]]; then
		CONFIG_FILE="/etc/apache2/sites-available/flaskapp.conf"
		WEB_USER="www-data"
	elif [[ "$FLAVOUR" = redhat ]]; then
		CONFIG_FILE="/etc/httpd/conf.d/flaskapp.conf"
		WEB_USER="apache"
	fi

	sed 's/%APP_NAME%/'$APP_NAME'/g;s/%HOSTNAME%/'$cliqrNodeHostname'/g;s|%WEB_ROOT%|'$WEB_ROOT'|g;s/%USER%/'$WEB_USER'/g' templates/apache-template.conf > "$CONFIG_FILE"

	# CentOS and Red Hat 6 require a tiny bit of extra config to work:
	if [[ "$FLAVOUR" == redhat ]]; then
		RH_VERSION=`rpm -qa \*-release|egrep 'centos|redhat'|cut -d"-" -f3`
		if (( $RH_VERSION <= 6 )); then
			echo 'WSGISocketPrefix /var/run/wsgi' >> "$CONFIG_FILE"
		fi
	fi

	log '[DEPLOY] Configured apache'

	# Enable the site if debian flavoured
	if [[ "$FLAVOUR" = debian ]]; then
		a2ensite flaskapp
	fi

	# Configure web root path
	mkdir -p $WEB_ROOT

	# Create wsgi file from template
	sed 's/%APP_NAME%/'$APP_NAME'/g;s/%HOSTNAME%/'$cliqrNodeHostname'/g;s|%WEB_ROOT%|'$WEB_ROOT'|g' templates/wsgi-template.wsgi > "$WEB_ROOT/$APP_NAME.wsgi"
	if (( $? > 0 )) || [[ ! -f flaskapp.zip ]]; then
		log '[ERROR] Script download failed'
		exit 127
	fi
	# Move python script(s) in to the same folder
	unzip -d "$WEB_ROOT" ./flaskapp.zip

	log '[DEPLOY] Completed deployment'
}

startservice() {
	log ['START'] Started service
	service $HTTPD_SERVICE start
	if (( $? > 0 )); then
		log '[ERROR] Service start failed'
		exit 127
	fi
}

stopservice() {
	log ['STOP'] Stopped service
	service $HTTPD_SERVICE stop
	if (( $? > 0 )); then
		log '[ERROR] Service stop failed'
		exit 127
	fi
}

restartservice() {
	log ['RESTART'] Restarted service
	service $HTTPD_SERVICE restart
	if (( $? > 0 )); then
		log '[ERROR] Service restart failed'
		exit 127
	fi
}

# Switch through CLI args
case $1 in
	install)
		# Run installation script
		install
		;;
	configure)
		# Configuration script
		;;
	deploy)
		# Run deployment script - i.e. init the service
		deploy
		;;
	start)
		# Run startup script
		startservice
		;;
	stop)
		# Run stop script
		stopservice
		;;
	restart)
		# Run restart script
		restartservice
		;;
	reload)
		# Run reload script - don't have one so just restart
		restartservice
		;;
	cleanup)
		# Run cleanup
		;;
	upgrade)
		# Run upgrade
		upgrade
		;;
	*)
		# Unknown command
		;;
esac
